In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv("econocausal_enriched_synthetic_dataset.csv")
print("Dataset loaded successfully!")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully!
Shape: (20000, 40)

,customer_id,age,income_bracket,urbanicity,region,tenure_months,historical_spend,recency_days,browsing_frequency,avg_session_duration_sec,...,days_since_last_campaign,marketing_contact_count_30d,discount_offered,discount_amount,purchased,basket_value_before_discount,revenue,cost_of_goods,marketing_cost,net_profit
0,100001,44,lower_middle,suburban,west,12,5502.94,4,5,168.9,...,23,3,10,91.95,0,919.46,0.00,0.00,4.50,-4.5
1,100002,39,lower_middle,suburban,west,7,4720.72,51,7,111.3,...,52,1,0,0.00,0,1500.40,0.00,0.00,1.50,-1.5
2,100003,26,lower_middle,rural,north,15,4656.31,12,6,343.7,...,3,2,0,0.00,0,453.77,0.00,0.00,3.00,-3.0
3,100004,25,low,rural,east,16,7174.15,13,10,136.4,...,40,2,10,133.99,1,1339.93,1205.94,905.95,136.99,163.0
4,100005,43,low,rural,west,22,2713.23,66,7,146.4,...,48,1,5,44.28,0,885.56,0.00,0.00,1.50,-1.5

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   20000 non-null  int64
 1   age                           20000 non-null  int64
 2   income_bracket                20000 non-null  object
 3   urbanicity                    20000 non-null  object
 4   region                        20000 non-null  object
 5   tenure_months                 20000 non-null  int64
 6   historical_spend              20000 non-null  float64
 7   recency_days                  20000 non-null  int64
 8   browsing_frequency            20000 non-null  int64
 9   avg_session_duration_sec      20000 non-null  float64
 10  cart_abandonment_rate         20000 non-null  float64
 11  support_tickets_count         20000 non-null  int64
 12  email_open_rate               20000 non-null  float64
 13  previous_discounts_accepted   20000 non-null  int64
 14  previous_purchases_12m        20000 non-null  int64
 15  avg_order_value               20000 non-null  float64
 16  website_visits_30d            20000 non-null  int64
 17  mobile_app_user               20000 non-null  int64
 18  loyalty_member                20000 non-null  int64
 19  subscription_status           20000 non-null  object
 20  preferred_channel             20000 non-null  object
 21  product_category              20000 non-null  object
 22  campaign_type                 20000 non-null  object
 23  day_of_week                   20000 non-null  object
 24  device_type                   20000 non-null  object
 25  competitor_price_index        20000 non-null  float64
 26  stock_availability            20000 non-null  object
 27  seasonality_index             20000 non-null  float64
 28  customer_satisfaction         20000 non-null  float64
 29  return_rate                   20000 non-null  float64
 30  days_since_last_campaign      20000 non-null  int64
 31  marketing_contact_count_30d   20000 non-null  int64
 32  discount_offered              20000 non-null  int64
 33  discount_amount               20000 non-null  float64
 34  purchased                     20000 non-null  int64
 35  basket_value_before_discount  20000 non-null  float64
 36  revenue                       20000 non-null  float64
 37  cost_of_goods                 20000 non-null  float64
 38  marketing_cost                20000 non-null  float64
 39  net_profit                    20000 non-null  float64
dtypes: float64(15), int64(15), object(10)
memory usage: 6.1+ MB

In [14]:
df.shape

(20000, 40)

In [15]:
df.dtypes

customer_id                       int64
age                               int64
income_bracket                   object
urbanicity                       object
region                           object
tenure_months                     int64
historical_spend                float64
recency_days                      int64
browsing_frequency                int64
avg_session_duration_sec        float64
cart_abandonment_rate           float64
support_tickets_count             int64
email_open_rate                 float64
previous_discounts_accepted       int64
previous_purchases_12m            int64
avg_order_value                 float64
website_visits_30d                int64
mobile_app_user                   int64
loyalty_member                    int64
subscription_status              object
preferred_channel                object
product_category                 object
campaign_type                    object
day_of_week                      object
device_type                      object
competitor_price_index          float64
stock_availability               object
seasonality_index               float64
customer_satisfaction           float64
return_rate                     float64
days_since_last_campaign          int64
marketing_contact_count_30d       int64
discount_offered                  int64
discount_amount                 float64
purchased                         int64
basket_value_before_discount    float64
revenue                         float64
cost_of_goods                   float64
marketing_cost                  float64
net_profit                      float64
dtype: object

In [16]:
df.isnull().sum()

customer_id                     0
age                             0
income_bracket                  0
urbanicity                      0
region                          0
tenure_months                   0
historical_spend                0
recency_days                    0
browsing_frequency              0
avg_session_duration_sec        0
cart_abandonment_rate           0
support_tickets_count           0
email_open_rate                 0
previous_discounts_accepted     0
previous_purchases_12m          0
avg_order_value                 0
website_visits_30d              0
mobile_app_user                 0
loyalty_member                  0
subscription_status             0
preferred_channel               0
product_category                0
campaign_type                   0
day_of_week                     0
device_type                     0
competitor_price_index          0
stock_availability              0
seasonality_index               0
customer_satisfaction           0
return_rate                     0
days_since_last_campaign        0
marketing_contact_count_30d     0
discount_offered                0
discount_amount                 0
purchased                       0
basket_value_before_discount    0
revenue                         0
cost_of_goods                   0
marketing_cost                  0
net_profit                      0
dtype: int64

In [17]:
df.describe()

,customer_id,age,tenure_months,historical_spend,recency_days,browsing_frequency,avg_session_duration_sec,cart_abandonment_rate,support_tickets_count,email_open_rate,...,days_since_last_campaign,marketing_contact_count_30d,discount_offered,discount_amount,purchased,basket_value_before_discount,revenue,cost_of_goods,marketing_cost,net_profit
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,110000.500000,36.231450,31.931350,4697.311133,33.938450,8.013700,225.596390,0.408680,1.100150,0.454065,...,27.539800,2.008950,8.750000,138.057008,0.284450,1580.251461,412.845859,271.286065,43.776132,97.783661
std,5773.647028,10.576232,19.621513,2103.322637,33.691309,2.790269,130.314799,0.194218,1.057155,0.195867,...,27.925974,1.429571,7.395285,161.234871,0.451163,965.740539,809.771617,534.537467,109.987695,254.100120
min,100001.000000,18.000000,1.000000,603.190000,0.000000,0.000000,10.000000,0.001000,0.000000,0.002000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,-791.900000
25%,105000.750000,28.000000,17.000000,3166.132500,9.000000,6.000000,130.300000,0.258000,0.000000,0.305000,...,8.000000,1.000000,3.750000,4.020000,0.000000,882.815000,0.000000,0.000000,1.500000,-4.500000
50%,110000.500000,36.000000,28.000000,4390.025000,23.000000,8.000000,201.750000,0.395000,1.000000,0.448000,...,19.000000,2.000000,7.500000,90.640000,0.000000,1371.180000,0.000000,0.000000,3.000000,-1.500000
75%,115000.250000,43.000000,43.000000,5876.940000,48.000000,10.000000,294.200000,0.548000,2.000000,0.598000,...,39.000000,3.000000,12.500000,195.025000,1.000000,2060.380000,546.897500,357.875000,7.500000,0.000000
max,120000.000000,75.000000,120.000000,19154.330000,180.000000,20.000000,1200.000000,0.977000,7.000000,0.969000,...,180.000000,11.000000,20.000000,1596.940000,1.000000,9652.160000,8204.620000,6154.590000,1596.940000,2937.120000

In [18]:

# 1. Duplicate checks
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

# 2. Treatment and outcome values
print("\nDiscount distribution:")
print(df["discount_offered"].value_counts(dropna=False).sort_index())

print("\nPurchase distribution:")
print(df["purchased"].value_counts(dropna=False).sort_index())

# 3. Binary outcome validation
print("\nInvalid purchased values:",
      (~df["purchased"].isin([0, 1])).sum())

# 4. Missing values (all columns)
print("\nColumns with missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# 5. Numeric columns with negative values
numeric_df = df.select_dtypes(include="number")
print("\nNegative values by numeric column:")
print((numeric_df < 0).sum()[(numeric_df < 0).sum() > 0])

# 6. Economic columns
economic_cols = [
    "discount_amount", "revenue", "cost_of_goods",
    "marketing_cost", "net_profit"
]
print("\nEconomic columns summary:")
print(df[economic_cols].describe().round(2))

Duplicate rows: 0
Duplicate customer IDs: 0

Discount distribution:
discount_offered
0     5000
5     5000
10    5000
20    5000
Name: count, dtype: int64

Purchase distribution:
purchased
0    14311
1     5689
Name: count, dtype: int64

Invalid purchased values: 0

Columns with missing values:
Series([], dtype: int64)

Negative values by numeric column:
net_profit    13152
dtype: int64

Economic columns summary:
       discount_amount   revenue  cost_of_goods  marketing_cost  net_profit
count         20000.00  20000.00       20000.00        20000.00    20000.00
mean            138.06    412.85         271.29           43.78       97.78
std             161.23    809.77         534.54          109.99      254.10
min               0.00      0.00           0.00            0.00     -791.90
25%               4.02      0.00           0.00            1.50       -4.50
50%              90.64      0.00           0.00            3.00       -1.50
75%             195.02    546.90         357.88            7.50        0.00
max            1596.94   8204.62        6154.59         1596.94     2937.12

In [19]:

import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles in current folder:")
print(os.listdir())

Current working directory:
c:\Users\Asus\OneDrive\Desktop\EconoCaualProject\EconoCausal

Files in current folder:
['.git', 'backend', 'docs', 'econocausal_enriched_synthetic_dataset_new', 'EconoCausal_project.ipynb', 'tests']

In [20]:

# Profit ko purchase status ke according compare karo
print(
    df.groupby("purchased")["net_profit"]
      .agg(["count", "mean", "min", "median", "max"])
      .round(2)
)

# Purchase status aur net-profit sign ka relationship
print("\nPurchase status vs profit sign:")
print(
    pd.crosstab(
        df["purchased"],
        df["net_profit"] < 0,
        margins=True
    )
)

# Zero-revenue rows ka profit
print("\nRows with zero revenue:")
print("Count:", (df["revenue"] == 0).sum())
print(
    df.loc[df["revenue"] == 0,
           ["purchased", "revenue", "cost_of_goods",
            "marketing_cost", "net_profit"]]
      .head(10)
)

           count    mean    min  median      max
purchased
0          14311   -3.04  -16.5   -3.00     0.00
1           5689  351.42 -791.9  272.39  2937.12

Purchase status vs profit sign:
net_profit  False   True    All
purchased
0            1889  12422  14311
1            4959    730   5689
All          6848  13152  20000

Rows with zero revenue:
Count: 14311
    purchased  revenue  cost_of_goods  marketing_cost  net_profit
0           0      0.0            0.0             4.5        -4.5
1           0      0.0            0.0             1.5        -1.5
2           0      0.0            0.0             3.0        -3.0
4           0      0.0            0.0             1.5        -1.5
5           0      0.0            0.0             7.5        -7.5
6           0      0.0            0.0             1.5        -1.5
8           0      0.0            0.0             1.5        -1.5
10          0      0.0            0.0             1.5        -1.5
12          0      0.0            0.0             3.0        -3.0
13          0      0.0            0.0             3.0        -3.0

In [21]:

# Check 1: Net profit formula
expected_profit = (
    df["revenue"]
    - df["cost_of_goods"]
    - df["marketing_cost"]
)

profit_diff = (df["net_profit"] - expected_profit).abs()

print("Net profit formula mismatches:", (profit_diff > 0.02).sum())
print("Maximum absolute difference:", round(profit_diff.max(), 4))


# Check 2: Revenue formula for purchased customers
buyers = df["purchased"] == 1

expected_revenue = (
    df.loc[buyers, "basket_value_before_discount"]
    - df.loc[buyers, "discount_amount"]
)

revenue_diff = (
    df.loc[buyers, "revenue"] - expected_revenue
).abs()

print("\nBuyer revenue mismatches:", (revenue_diff > 0.02).sum())
print("Maximum revenue difference:", round(revenue_diff.max(), 4))


# Check 3: Negative-profit purchasers
negative_buyers = df[
    (df["purchased"] == 1) & (df["net_profit"] < 0)
]

print("\nPurchasers with negative profit:", len(negative_buyers))
print(
    negative_buyers[
        ["discount_offered", "discount_amount",
         "basket_value_before_discount", "revenue",
         "cost_of_goods", "marketing_cost", "net_profit"]
    ].head(10).to_string(index=False)
)

Net profit formula mismatches: 0
Maximum absolute difference: 0.0

Buyer revenue mismatches: 0
Maximum revenue difference: 0.0

Purchasers with negative profit: 730
 discount_offered  discount_amount  basket_value_before_discount  revenue  cost_of_goods  marketing_cost  net_profit
               20           163.75                        818.73   654.98         515.91          169.75      -30.68
               20           101.53                        507.66   406.13         315.76          106.03      -15.66
               20           509.08                       2545.42  2036.34        1607.35          512.08      -83.09
               20           362.24                       1811.21  1448.97        1090.46          369.74      -11.23
               20           194.81                        974.04   779.23         678.13          196.31      -95.21
               20           245.02                       1225.08   980.06         880.29          245.02     -145.25
               20            84.36                        421.79   337.43         256.35           88.86       -7.78
               20           312.07                       1560.36  1248.29         934.28          316.57       -2.56
               20           427.55                       2137.77  1710.22        1375.05          433.55      -98.38
               20           457.20                       2286.00  1828.80        1436.86          460.20      -68.26

In [22]:

# Purchase rate for each discount level
purchase_summary = (
    df.groupby("discount_offered")
      .agg(
          customers=("customer_id", "count"),
          purchases=("purchased", "sum"),
          purchase_rate=("purchased", "mean"),
          avg_revenue=("revenue", "mean"),
          avg_profit=("net_profit", "mean")
      )
)

purchase_summary["purchase_rate_pct"] = (
    purchase_summary["purchase_rate"] * 100
).round(2)

print(purchase_summary.round(3))

# Discount levels should be exactly the expected categories
print("\nDiscount levels:", sorted(df["discount_offered"].unique()))
print("Purchase values:", sorted(df["purchased"].unique()))

                  customers  purchases  purchase_rate  avg_revenue  \
discount_offered
0                      5000       1353          0.271      429.294
5                      5000       1411          0.282      429.355
10                     5000       1477          0.295      415.657
20                     5000       1448          0.290      377.076

                  avg_profit  purchase_rate_pct
discount_offered
0                    168.794              27.06
5                    133.869              28.22
10                    89.696              29.54
20                    -1.224              28.96

Discount levels: [np.int64(0), np.int64(5), np.int64(10), np.int64(20)]
Purchase values: [np.int64(0), np.int64(1)]

In [23]:

# Check relationship between discount and marketing costs
print(
    df.groupby("discount_offered")[
        ["discount_amount", "marketing_cost", "revenue",
         "cost_of_goods", "net_profit"]
    ].mean().round(2)
)

print("\nMarketing cost minus discount amount:")
print(
    (df["marketing_cost"] - df["discount_amount"])
    .describe()
    .round(2)
)

print("\nCorrelation between discount and marketing cost:")
print(
    df[["discount_amount", "marketing_cost"]]
    .corr()
    .round(3)
)

                  discount_amount  marketing_cost  revenue  cost_of_goods  \
discount_offered
0                            0.00            3.01   429.29         257.49
5                           79.45           25.62   429.36         269.87
10                         156.30           49.17   415.66         276.79
20                         316.47           97.30   377.08         281.00

                  net_profit
discount_offered
0                     168.79
5                     133.87
10                     89.70
20                     -1.22

Marketing cost minus discount amount:
count    20000.00
mean       -94.28
std        147.73
min      -1521.71
25%       -138.68
50%        -31.52
75%          3.00
max         16.50
dtype: float64

Correlation between discount and marketing cost:
                 discount_amount  marketing_cost
discount_amount            1.000           0.459
marketing_cost             0.459           1.000

In [24]:

# Check the exact accounting identity
df["calculated_profit"] = (
    df["revenue"]
    - df["cost_of_goods"]
    - df["marketing_cost"]
)

df["profit_difference"] = (
    df["net_profit"] - df["calculated_profit"]
)

print("Formula mismatches:",
      (df["profit_difference"].abs() > 0.01).sum())

print("\nSample rows:")
print(
    df[[
        "discount_offered",
        "discount_amount",
        "revenue",
        "cost_of_goods",
        "marketing_cost",
        "net_profit",
        "calculated_profit",
        "profit_difference"
    ]].head(10).round(2)
)

Formula mismatches: 0

Sample rows:
   discount_offered  discount_amount  revenue  cost_of_goods  marketing_cost  \
0                10            91.95     0.00           0.00            4.50
1                 0             0.00     0.00           0.00            1.50
2                 0             0.00     0.00           0.00            3.00
3                10           133.99  1205.94         905.95          136.99
4                 5            44.28     0.00           0.00            1.50
5                 0             0.00     0.00           0.00            7.50
6                 0             0.00     0.00           0.00            1.50
7                10            55.22   497.01         275.44           56.72
8                 0             0.00     0.00           0.00            1.50
9                10            98.42   885.81         582.74          101.42

   net_profit  calculated_profit  profit_difference
0       -4.50              -4.50                0.0
1       -1.50              -1.50                0.0
2       -3.00              -3.00                0.0
3      163.00             163.00                0.0
4       -1.50              -1.50                0.0
5       -7.50              -7.50                0.0
6       -1.50              -1.50                0.0
7      164.85             164.85                0.0
8       -1.50              -1.50                0.0
9      201.65             201.65                0.0

In [25]:

profit_breakdown = (
    df.groupby(["discount_offered", "purchased"])
      .agg(
          customers=("customer_id", "count"),
          avg_revenue=("revenue", "mean"),
          avg_cost_of_goods=("cost_of_goods", "mean"),
          avg_marketing_cost=("marketing_cost", "mean"),
          avg_net_profit=("net_profit", "mean")
      )
      .round(2)
)

print(profit_breakdown)

                            customers  avg_revenue  avg_cost_of_goods  \
discount_offered purchased
0                0               3647         0.00               0.00
                 1               1353      1586.45             951.55
5                0               3589         0.00               0.00
                 1               1411      1521.46             956.29
10               0               3523         0.00               0.00
                 1               1477      1407.10             936.99
20               0               3552         0.00               0.00
                 1               1448      1302.06             970.31

                            avg_marketing_cost  avg_net_profit
discount_offered purchased
0                0                        3.03           -3.03
                 1                        2.95          631.95
5                0                        3.04           -3.04
                 1                       83.05          482.12
10               0                        3.03           -3.03
                 1                      159.24          310.86
20               0                        3.07           -3.07
                 1                      328.44            3.31

In [26]:

import json

with open("EconoCausal_project.ipynb", "r", encoding="utf-8") as f:
    notebook = json.load(f)

keywords = [
    "discount_offered",
    "discount_amount",
    "marketing_cost",
    "net_profit",
    "recency_days",
    "customer_satisfaction",
]

for i, cell in enumerate(notebook["cells"]):
    source = "".join(cell.get("source", []))
    if cell["cell_type"] == "code" and any(
        keyword in source for keyword in keywords
    ):
        print(f"\n--- Cell {i} ---")
        print(source[:2500])

--- Cell 7 ---

# 1. Duplicate checks
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

# 2. Treatment and outcome values
print("\nDiscount distribution:")
print(df["discount_offered"].value_counts(dropna=False).sort_index())

print("\nPurchase distribution:")
print(df["purchased"].value_counts(dropna=False).sort_index())

# 3. Binary outcome validation
print("\nInvalid purchased values:",
      (~df["purchased"].isin([0, 1])).sum())

# 4. Missing values (all columns)
print("\nColumns with missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# 5. Numeric columns with negative values
numeric_df = df.select_dtypes(include="number")
print("\nNegative values by numeric column:")
print((numeric_df < 0).sum()[(numeric_df < 0).sum() > 0])

# 6. Economic columns
economic_cols = [
    "discount_amount", "revenue", "cost_of_goods",
    "marketing_cost", "net_profit"
]
print("\nEconomic columns summary:")
print(df[economic_cols].describe().round(2))



--- Cell 9 ---

# Profit ko purchase status ke according compare karo
print(
    df.groupby("purchased")["net_profit"]
      .agg(["count", "mean", "min", "median", "max"])
      .round(2)
)

# Purchase status aur net-profit sign ka relationship
print("\nPurchase status vs profit sign:")
print(
    pd.crosstab(
        df["purchased"],
        df["net_profit"] < 0,
        margins=True
    )
)

# Zero-revenue rows ka profit
print("\nRows with zero revenue:")
print("Count:", (df["revenue"] == 0).sum())
print(
    df.loc[df["revenue"] == 0,
           ["purchased", "revenue", "cost_of_goods",
            "marketing_cost", "net_profit"]]
      .head(10)
)


--- Cell 10 ---

# Check 1: Net profit formula
expected_profit = (
    df["revenue"]
    - df["cost_of_goods"]
    - df["marketing_cost"]
)

profit_diff = (df["net_profit"] - expected_profit).abs()

print("Net profit formula mismatches:", (profit_diff > 0.02).sum())
print("Maximum absolute difference:", round(profit_diff.max(), 4))


# Check 2: Revenue formula for purchased customers
buyers = df["purchased"] == 1

expected_revenue = (
    df.loc[buyers, "basket_value_before_discount"]
    - df.loc[buyers, "discount_amount"]
)

revenue_diff = (
    df.loc[buyers, "revenue"] - expected_revenue
).abs()

print("\nBuyer revenue mismatches:", (revenue_diff > 0.02).sum())
print("Maximum revenue difference:", round(revenue_diff.max(), 4))


# Check 3: Negative-profit purchasers
negative_buyers = df[
    (df["purchased"] == 1) & (df["net_profit"] < 0)
]

print("\nPurchasers with negative profit:", len(negative_buyers))
print(
    negative_buyers[
        ["discount_offered", "discount_amount",
         "basket_value_before_discount", "revenue",
         "cost_of_goods", "marketing_cost", "net_profit"]
    ].head(10).to_string(index=False)
)


--- Cell 11 ---

# Purchase rate for each discount level
purchase_summary = (
    df.groupby("discount_offered")
      .agg(
          customers=("customer_id", "count"),
          purchases=("purchased", "sum"),
          purchase_rate=("purchased", "mean"),
          avg_revenue=("revenue", "mean"),
          avg_profit=("net_profit", "mean")
      )
)

purchase_summary["purchase_rate_pct"] = (
    purchase_summary["purchase_rate"] * 100
).round(2)

print(purchase_summary.round(3))

# Discount levels should be exactly the expected categories
print("\nDiscount levels:", sorted(df["discount_offered"].unique()))
print("Purchase values:", sorted(df["purchased"].unique()))


--- Cell 12 ---

# Check relationship between discount and marketing costs
print(
    df.groupby("discount_offered")[
        ["discount_amount", "marketing_cost", "revenue",
         "cost_of_goods", "net_profit"]
    ].mean().round(2)
)

print("\nMarketing cost minus discount amount:")
print(
    (df["marketing_cost"] - df["discount_amount"])
    .describe()
    .round(2)
)

print("\nCorrelation between discount and marketing cost:")
print(
    df[["discount_amount", "marketing_cost"]]
    .corr()
    .round(3)
)


--- Cell 13 ---

# Check the exact accounting identity
df["calculated_profit"] = (
    df["revenue"]
    - df["cost_of_goods"]
    - df["marketing_cost"]
)

df["profit_difference"] = (
    df["net_profit"] - df["calculated_profit"]
)

print("Formula mismatches:",
      (df["profit_difference"].abs() > 0.01).sum())

print("\nSample rows:")
print(
    df[[
        "discount_offered",
        "discount_amount",
        "revenue",
        "cost_of_goods",
        "marketing_cost",
        "net_profit",
        "calculated_profit",
        "profit_difference"
    ]].head(10).round(2)
)


--- Cell 14 ---

profit_breakdown = (
    df.groupby(["discount_offered", "purchased"])
      .agg(
          customers=("customer_id", "count"),
          avg_revenue=("revenue", "mean"),
          avg_cost_of_goods=("cost_of_goods", "mean"),
          avg_marketing_cost=("marketing_cost", "mean"),
          avg_net_profit=("net_profit", "mean")
      )
      .round(2)
)

print(profit_breakdown)

In [27]:

for i, cell in enumerate(notebook["cells"]):
    source = "".join(cell.get("source", []))
    if cell["cell_type"] == "code" and (
        "discount_offered" in source
        and any(word in source.lower() for word in [
            "np.random", "random", "assign", "probability",
            "choice(", "def "
        ])
    ):
        print(f"\n--- Cell {i} ---")
        print(source[:4000])

In [28]:

for i, cell in enumerate(notebook["cells"]):
    source = "".join(cell.get("source", []))
    if "discount_offered" in source:
        print(f"\n--- Cell {i} ---")
        print(source[:3000])

--- Cell 7 ---

# 1. Duplicate checks
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

# 2. Treatment and outcome values
print("\nDiscount distribution:")
print(df["discount_offered"].value_counts(dropna=False).sort_index())

print("\nPurchase distribution:")
print(df["purchased"].value_counts(dropna=False).sort_index())

# 3. Binary outcome validation
print("\nInvalid purchased values:",
      (~df["purchased"].isin([0, 1])).sum())

# 4. Missing values (all columns)
print("\nColumns with missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

# 5. Numeric columns with negative values
numeric_df = df.select_dtypes(include="number")
print("\nNegative values by numeric column:")
print((numeric_df < 0).sum()[(numeric_df < 0).sum() > 0])

# 6. Economic columns
economic_cols = [
    "discount_amount", "revenue", "cost_of_goods",
    "marketing_cost", "net_profit"
]
print("\nEconomic columns summary:")
print(df[economic_cols].describe().round(2))



--- Cell 10 ---

# Check 1: Net profit formula
expected_profit = (
    df["revenue"]
    - df["cost_of_goods"]
    - df["marketing_cost"]
)

profit_diff = (df["net_profit"] - expected_profit).abs()

print("Net profit formula mismatches:", (profit_diff > 0.02).sum())
print("Maximum absolute difference:", round(profit_diff.max(), 4))


# Check 2: Revenue formula for purchased customers
buyers = df["purchased"] == 1

expected_revenue = (
    df.loc[buyers, "basket_value_before_discount"]
    - df.loc[buyers, "discount_amount"]
)

revenue_diff = (
    df.loc[buyers, "revenue"] - expected_revenue
).abs()

print("\nBuyer revenue mismatches:", (revenue_diff > 0.02).sum())
print("Maximum revenue difference:", round(revenue_diff.max(), 4))


# Check 3: Negative-profit purchasers
negative_buyers = df[
    (df["purchased"] == 1) & (df["net_profit"] < 0)
]

print("\nPurchasers with negative profit:", len(negative_buyers))
print(
    negative_buyers[
        ["discount_offered", "discount_amount",
         "basket_value_before_discount", "revenue",
         "cost_of_goods", "marketing_cost", "net_profit"]
    ].head(10).to_string(index=False)
)


--- Cell 11 ---

# Purchase rate for each discount level
purchase_summary = (
    df.groupby("discount_offered")
      .agg(
          customers=("customer_id", "count"),
          purchases=("purchased", "sum"),
          purchase_rate=("purchased", "mean"),
          avg_revenue=("revenue", "mean"),
          avg_profit=("net_profit", "mean")
      )
)

purchase_summary["purchase_rate_pct"] = (
    purchase_summary["purchase_rate"] * 100
).round(2)

print(purchase_summary.round(3))

# Discount levels should be exactly the expected categories
print("\nDiscount levels:", sorted(df["discount_offered"].unique()))
print("Purchase values:", sorted(df["purchased"].unique()))


--- Cell 12 ---

# Check relationship between discount and marketing costs
print(
    df.groupby("discount_offered")[
        ["discount_amount", "marketing_cost", "revenue",
         "cost_of_goods", "net_profit"]
    ].mean().round(2)
)

print("\nMarketing cost minus discount amount:")
print(
    (df["marketing_cost"] - df["discount_amount"])
    .describe()
    .round(2)
)

print("\nCorrelation between discount and marketing cost:")
print(
    df[["discount_amount", "marketing_cost"]]
    .corr()
    .round(3)
)


--- Cell 13 ---

# Check the exact accounting identity
df["calculated_profit"] = (
    df["revenue"]
    - df["cost_of_goods"]
    - df["marketing_cost"]
)

df["profit_difference"] = (
    df["net_profit"] - df["calculated_profit"]
)

print("Formula mismatches:",
      (df["profit_difference"].abs() > 0.01).sum())

print("\nSample rows:")
print(
    df[[
        "discount_offered",
        "discount_amount",
        "revenue",
        "cost_of_goods",
        "marketing_cost",
        "net_profit",
        "calculated_profit",
        "profit_difference"
    ]].head(10).round(2)
)


--- Cell 14 ---

profit_breakdown = (
    df.groupby(["discount_offered", "purchased"])
      .agg(
          customers=("customer_id", "count"),
          avg_revenue=("revenue", "mean"),
          avg_cost_of_goods=("cost_of_goods", "mean"),
          avg_marketing_cost=("marketing_cost", "mean"),
          avg_net_profit=("net_profit", "mean")
      )
      .round(2)
)

print(profit_breakdown)